name: elangkuy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # Tambahkan dependencies yang mungkin diperlukan
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0  # Optional: Alternatif untuk download manual font Inter
  shared_preferences: ^2.2.2  # Tambahkan baris ini
  http: ^1.4.0
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Tambahkan konfigurasi assets 
  assets:
    - assets/images/
    - assets/icons/
  
  # Tambahkan konfigurasi font Inter
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700